<?php

/**
 * This file is part of base application with Laminas MVC framework
 * 
 * This file is a view partial script for the main navigationbar.
 * Use this partial with Laminas\View\Helper\Navigation\Menu.
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @link       https://github.com/nik-web/base-application
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<button class="hamburg">
    <span class="hamburg-line"></span>
    <span class="hamburg-line"></span>
    <span class="hamburg-line"></span>
</button>
<ul id="main-nav-bar">
<?php
    foreach ($container as $page) {
        if (!$this->navigation('Laminas\Navigation\Main')->accept($page)) {
            continue;  
        }
        if (!$page->hasPages()) {
            if ($page->isActive()) {
?>
    <li class="main-nav-item-current">
        <strong>
            <?=  $page ?>
        </strong>
    </li>
<?php
            } else {
?>
    <li class="main-nav-item">
        <a class="main-nav-link" href="<?= $page->getHref() ?>">
            <?=  $page ?>
        </a>
    </li>
<?php
            }
        } else {
?>
    <li class="main-nav-item-dropdown">
        <?php
            $classValue = 'main-nav-button';
            foreach ($page->getPages() as $child) {
                if (!$this->navigation()->accept($child)) {
                    continue;
                }
                if ($child->isActive()) {
                    $classValue = 'main-nav-button-active';
                }
            }
        ?>
        <button id="<?= $page->getId(); ?>" class="<?= $classValue; ?>">
            <?= $page . ' &darr;' ?>
        </button>
        <ul id="<?= $page->getId() . '-menu' ?>" class="main-nav-bar-dropdown">
        <?php
            foreach ($page->getPages() as $child) {
                if (!$this->navigation()->accept($child)) {
                    continue;
                }
                if ($child->isActive()) {
        ?>
            <li class="main-nav-dropdown-item-current">
                <strong>
                    <?= $child ?>
                </strong>
            </li>
            <?php
                } else {
            ?>
            <li class="main-nav-dropdown-item">
                <a class="main-nav-link" href="<?= $child->getHref() ?>">
                    <?= $child ?>
                </a>
            </li>
            <?php
                }      
            }
        ?>
        </ul>
    </li>
<?php
        }
    }
?>
</ul>