<?php

/**
 * Base application with Laminas MVC framework
 * 
 * Error template
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @version    1.0.0
 * @since      1.0.0
 */

$this->headTitle('Ein Fehler ist aufgetreten');
$description = 'Das ist die Meta-Beschreibung für die Fehlerseite dieser Webanwendung';
$keywords = 'Webanwendung, Fehler, aufgetreten, Fehlerseite';
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

if (empty($this->display_exceptions)) {
?>
<h1>
    Ein Fehler ist aufgetreten
</h1>
<p>
    Hier ist der Inhalt der Fehlerseite für den Nutzer!!!
</p>
<?php
} else {
?>
<h1>
    An error occurred
</h1>
<h2>
    <?= $this->message ?>
</h2>
<?php
    if (isset($this->exception) && $this->exception instanceof \Throwable) {
?>
<hr>
<h2>
    Additional information:
</h2>
<h3>
    <?= get_class($this->exception) ?>
</h3>
<dl>
    <dt>File:</dt>
    <dd>
        <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
    </dd>
    <dt>Message:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getMessage()) ?></pre>
    </dd>
    <dt>Stack trace:</dt>
    <dd>
        <pre><?= $this->escapeHtml($this->exception->getTraceAsString()) ?></pre>
    </dd>
</dl>
<?php 
        if ($ex = $this->exception->getPrevious()) {
?>
<hr/>
<h2>
    Previous exceptions:
</h2>
<ul class="list-unstyled">
<?php
    $icount = 0;
    while ($ex) {
?>
    <li>
        <h3>
            <?= get_class($ex) ?>
        </h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $ex->getFile() ?>:<?= $ex->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getMessage()) ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $this->escapeHtml($ex->getTraceAsString()) ?></pre>
            </dd>
        </dl>
    </li>
<?php
        $ex = $ex->getPrevious();
        if (++$icount >= 50) {
            echo '<li>There may be more exceptions, but we do not have enough memory to process it.</li>';
            break;
        }
    }
?>
</ul>
<?php
        }
    } else {
?>
<h3>No Exception available</h3>
<?php
    }
}
?>