<?php

/**
 * This file is part of base application with Laminas MVC framework
 * 
 * This is the default layout (layout/layout) template of this web application
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @link       https://github.com/nik-web/base-application
 * @license    https://opensource.org/licenses/BSD-3-Clause The BSD-3-Clause License
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<?= $this->doctype() ?>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle()->setAutoEscape(false) . "\n" ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?= $this->headMeta() . "\n" ?>
        <?=
        $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/styles.css'));
        ?>
    </head>
    <body>
        <header id="site-header">
            <div class="site-width-container">
                <?= $this->navigation('Laminas\Navigation\Brand')->menu()->setPartial('partial/nav-bar/brand') . "\n"  ?>
            </div>
        </header>
        <nav id="site-nav">
            <div class="site-width-container">
                <?= $this->navigation('Laminas\Navigation\Main')->menu()->setPartial('partial/nav-bar/main') . "\n"  ?>
            </div>
        </nav>
        <div id="site-flex" class="site-width-container">
            <main>        
                <?= $this->content ?>
            </main>
        </div>
        <footer id="site-footer">
            <div class="site-width-container">
                <?= $this->navigation('Laminas\Navigation\Meta')->menu()->setPartial('partial/nav-bar/meta') . "\n"  ?>
            </div>
            <small id="copyright-notice">
                <?= $this->copyright_notice()->render(); ?>
            </small>
        </footer>
        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/main.js'), '');
        ?>
    </body>
</html>