<?php

/**
 * Base application with Laminas MVC framework
 * 
 * Home template
 * 
 * @package    Application
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @copyright  Copyright (c) Niklaus Höpfner
 * @version    1.0.0
 * @since      1.0.0
 */

$this->headTitle('Das ist die Startseite unserer Webanwendung');
$description = 'Das ist die Meta-Beschreibung der Startseite dieser Webanwendung';
$keywords = 'Webanwendung, Startseite,';
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
?>
<header id="main-header">
    <h1>
        Startseite
    </h1>
    <p>
        Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, 
        eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.
    </p>
</header>
<p>
    Lorem ipsum dolor <strong>Das ist mit Strong hervorgehoben </strong>sit amet,
    consectetuer adipiscing elit. Aenean commodo 
    ligula <a href="#" title="Das ist ein Textlink">Das ist ein Textlink</a> 
    eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis 
    parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec,
    pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec 
    pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, 
    rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede 
    mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. 
    Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, 
    eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. 
    Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet.
</p>
<ul>
    <li>Suchmaschinen
        <ul>
            <li>Google</li>
            <li>Bing</li>
            <li>Ask.com</li>
        </ul>
    </li>
    <li>Verzeichnisse
        <ul>
            <li>Yahoo</li>
            <li>Web.de</li>
        </ul>
    </li>
    <li>Was anderes</li>
    <li>Noch was anderes</li>
</ul>
<button name="button">Press me</button>

<div>
    <label for="ice-cream-choice">
        Choose a flavor:
    </label>
    
    <input list="ice-cream-flavors" id="ice-cream-choice" name="ice-cream-choice" />

    <datalist id="ice-cream-flavors">
        <option value="Chocolate">
        <option value="Coconut">
        <option value="Mint">
        <option value="Strawberry">
        <option value="Vanilla">
    </datalist>
</div>
    